default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: lacey-dawn-photography_development


test:
  <<: *default
  database: lacey-dawn-photography_test


production:
  <<: *default
  database: lacey-dawn-photography_production