# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create(email: "lacey.hike@gmail.com", password: "password", password_confirmation: "password", user_type: 1)

def create_items
  Item.find_or_create_by(name: "Lustre", photo_type: "Photo")
  Item.find_or_create_by(name: "Glossy", photo_type: "Photo")
  Item.find_or_create_by(name: "Metallic", photo_type: "Photo")
  Item.find_or_create_by(name: "Deep Matte", photo_type: "Photo")
  Item.find_or_create_by(name: "Pearl", photo_type: "Photo")
  Item.find_or_create_by(name: "Glossy Coating & Satin", photo_type: "Photo")
  Item.find_or_create_by(name: "Glossy Plastic Laminate", photo_type: "Photo")
  Item.find_or_create_by(name: "Canvas", photo_type: "Photo")
  Item.find_or_create_by(name: "Pebble", photo_type: "Photo")
  Item.find_or_create_by(name: "Linen", photo_type: "Photo")
  Item.find_or_create_by(name: "Styrene", photo_type: "Photo")
  Item.find_or_create_by(name: "Gator Board", photo_type: "Photo")
  Item.find_or_create_by(name: "Masonite", photo_type: "Photo")
  Item.find_or_create_by(name: "Other", photo_type: "Photo")
  Item.find_or_create_by(name: "Presentation - Boutique Packaging")
  Item.find_or_create_by(name: "Presentation - Wood Box")
  Item.find_or_create_by(name: "Presentation - Bay Box")
  Item.find_or_create_by(name: "Presentation - Image Folio")
  Item.find_or_create_by(name: "Presentation - CD/DVD")
  Item.find_or_create_by(name: "Presentation - USB Cases & Drives")
  Item.find_or_create_by(name: "Wall Display - Metal")
  Item.find_or_create_by(name: "Wall Display - Acrylic")
  Item.find_or_create_by(name: "Wall Display - Canvas")
  Item.find_or_create_by(name: "Wall Display - Framed")
  Item.find_or_create_by(name: "Wall Display - Wood")
  Item.find_or_create_by(name: "Wall Display - Xpozer")
  Item.find_or_create_by(name: "Wall Display - Standout")
  Item.find_or_create_by(name: "Wall Display - Bamboo")
  Item.find_or_create_by(name: "Wall Display - intensiTiles")
  Item.find_or_create_by(name: "Wall Display - Thin Wraps")
  Item.find_or_create_by(name: "Wall Display - Clusters")
  Item.find_or_create_by(name: "Wall Display - Splits")
  Item.find_or_create_by(name: "Wall Display - Collage Wall")
  Item.find_or_create_by(name: "Wall Display - Gallery Blocks")
  Item.find_or_create_by(name: "Books - Wave Books")
  Item.find_or_create_by(name: "Books - Bay Books")
  Item.find_or_create_by(name: "Calendar - Photo Paper")
  Item.find_or_create_by(name: "Calendar - Press Printed")
  Item.find_or_create_by(name: "Cards - Press Printed")
  Item.find_or_create_by(name: "Cards - Photo Paper")
  Item.find_or_create_by(name: "Cards - Envelopes")
  Item.find_or_create_by(name: "Cards - Stickers & Labels")
  Item.find_or_create_by(name: "Holiday - Cards")
  Item.find_or_create_by(name: "Holiday - Ornaments")
  Item.find_or_create_by(name: "Holiday - Gift Tags & Holiday Magnets")
  Item.find_or_create_by(name: "Gifts - Magnets")
  Item.find_or_create_by(name: "Gifts - Ornaments")
  Item.find_or_create_by(name: "Gifts - Coasters")
  Item.find_or_create_by(name: "Gifts - Bookmarks")
  Item.find_or_create_by(name: "Gifts - Device Cases")
end

create_items